"""Initial migration

Revision ID: 795e70dc0018
Revises: 
Create Date: 2025-06-19 09:45:31.279467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795e70dc0018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('Collaborateur', 'Manager', 'RH', name='role_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objet', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('date_retour', sa.Date(), nullable=False),
    sa.Column('nb_nuitees', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('etat', sa.Enum('En attente', 'Validée', 'Refusée', name='etat_mission_enum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_frais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('type_frais', sa.Enum('Hôtel', 'Kilométrage', 'Péage', 'Repas', 'Parking', 'Train', 'Taxi', name='typefrais_enum'), nullable=False),
    sa.Column('justificatif', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.Enum('En attente', 'Validée', 'Refusée', name='etat_frais_enum'), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('commentaire', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.String(length=50), nullable=False),
    sa.Column('note_frais_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('validateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.ForeignKeyConstraint(['note_frais_id'], ['note_frais.id'], ),
    sa.ForeignKeyConstraint(['validateur_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historique')
    op.drop_table('note_frais')
    op.drop_table('mission')
    op.drop_table('user')
    # ### end Alembic commands ###
